### ISSUE TITLE
Continuous authorization

### ISSUE THREAD

**Issue by KingIdee** [pusher/android-slack-clone#1]
I think you should review how the authorization is done. It keeps redirecting me to the GitHub authorization page even after I just got authorized. I tried on two devices. As a result, I cant go past the entry activity. Did this happen to you too?

**Comment by pablisco** [comment]
Should be fixed by this commit: https://github.com/pusher/android-slack-clone/commit/58f48e909db18e497decc18364af0bc103d5d550

**Comment by KingIdee** [comment]
Surprisingly, it didn't. I noticed there were multiple calls made to the `onNewIntent` function. That should be as a result of the `launchMode` used.

**Comment by pablisco** [comment]
Did you try uninstalling the app and revoking access to the app on github (only if there is one present on your account)?

**Comment by pablisco** [comment]
@KingIdee Ok, it should be working again (not very elegantly though)

**Comment by KingIdee** [comment]
Still not working on my end. Where you able to reproduce the error? I uninstalled the app, revoked Chatkit's access and I'm still experiencing it. Let me try to fix it at my end and make a PR

**Comment by KingIdee** [comment]
Is the authentication smooth at your end?

**Comment by TobiAlbert** [comment]
I'm still facing this issue, on my end.
